development:
  dialect: postgres
  datasource: host=localhost dbname=tester user=genome password=genome sslmode=disable
  dir: migrationsx
  table: migrations

production:
  dialect: postgres
  datasource: host=localhost dbname=tester user=genome password=genome sslmode=disable
  dir: /etc/prod-template/migrations
  table: migrations