server:
  http_listen_port: ${PROMTAIL_PORT}
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
- url: ${LOKI_SERVER_URL}

scrape_configs:
  - job_name: systemd-journald
    journal:
      json: false
      path: /var/log/journal
      labels:
        job: "systemd-journald"
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: "prod-template.service"
        action: keep
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
